#!/bin/bash
# Script to start interactive job on ARC systems
# Only for clusters managed by Slurm

original_args="$@";
unset p_flag
unset A_flag
unset gres_flag
unset gres
unset partition


while (( $# )); do
  case "$1" in
    -p )
      p_flag="$2";
      shift 2
    ;;
    --partition=* )
      p_flag=$(echo $1 | cut -d "=" -f 2);
      shift
    ;;
    -A )
      A_flag=true;
      shift 2
    ;;
    --account=* )
      A_flag=true;
      shift
    ;;
    --gres=* )
      gres_flag=true;
      shift
    ;;
    * ) break ;;
  esac
done

# If account not specified by user
if [ -z "$A_flag" ]
then
  # Get default account for user from Slurm
  account=`scontrol show assoc users=$USER flags=users | grep -E -o "DefAccount=\S*" | tr = " " | awk '{print $2}'`
  # Detect account = "(null)"
  if [[ "$account" = "(null)" ]]
  then
    echo "Could not find a default account/allocation for $USER. Quitting."
    exit 1
  fi
  echo "Using $account, the default allocation/account for $USER."
fi

if [ -n "$p_flag" ]
then
  # If user requests a v100 node, make sure they also get a gpu allocated
  if echo "$p_flag" | grep -q "^v100_\w\+_q$\|^k80_q$" && [[ -z "$gres_flag" ]]
    then
    echo " --- GPU partition/queue specified, but no GPU requested: adding --gres=gpu:1"
    gres="--gres=gpu:1"
    partition=""
  fi
  # all jobs on HU get a GPU and go to normal_q
elif [[ "$SYSNAME" = "huckleberry" ]]
  then
  echo " --- setting --partition=normal_q and --gres=gpu:1"
  partition="--partition=normal_q"
  gres="--gres=gpu:1"
else
  echo " --- No partition/queue specified: setting --partition=dev_q"
  partition="--partition=dev_q"
fi

# Unspecified defaults apply as follows, by may be over-ridden by explicityly specifying them
# --nodes=1
# --ntasks=1
# --time=00:30:00
# --partition=dev_q
# --job-name=interact
salloc $partition $gres --job-name="INTERACT" $original_args
